# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "threatnote"
  config.vm.box = "trusty-server"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"

  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.network "forwarded_port", guest: 7777, host: 7777

  config.vm.synced_folder "../", "/threatnote"

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe "mongodb-10gen::single"
    chef.add_recipe "apt"
    chef.add_recipe "build-essential"
    chef.add_recipe "threatnote"
  end

end
