#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'mongodb-10gen', :path => './'
cookbook 'simplelog_handler', :git => 'https://github.com/higanworks-cookbooks/simplelog_handler'
