name             "mongodb-10gen"
maintainer       "Higanworks LLC."
maintainer_email "sawanoboriyu@higanworks.com"
license          "MIT"
description      "Installs/Configures mongodb-10gen"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.2.1"
depends          "apt", ">= 2.5.0"
supports         "ubuntu"
supports         "debian"
